#!/usr/bin/env python3
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

def render(lane: str) -> str:
    current=json.loads((ROOT/"workflow/CURRENT.json").read_text(encoding="utf-8"))
    status=json.loads((ROOT/"productions/quality-status.json").read_text(encoding="utf-8"))
    docs=[]
    brief_path=str((current.get("lane_briefs") or {}).get(lane) or "")
    for p in list(current.get("core_docs") or [])+list((current.get("lane_docs") or {}).get(lane) or []):
        if p != brief_path and p not in docs: docs.append(p)
    fast_start=list((current.get("lane_fast_start") or {}).get(lane) or [])
    if not fast_start:
        raise ValueError(f"workflow/CURRENT.json has no lane_fast_start for {lane}")
    rows=[]
    for item in status.get("productions",[]):
        if item.get("current") and item.get("lane", "cinematic") == lane:
            rows.append(f"| {item['title']} | {item['user_quality_status']} | {'yes' if item['keep_working'] else 'no'} | {'yes' if item['baseline_promoted'] else 'no'} |")
    fast_lines="\n".join(f"{index}. {item}" for index,item in enumerate(fast_start,1))
    return f"""# {lane.title()} lane brief

> Generated by `scripts/generate-lane-brief.py`. Canonical policy remains `workflow/CURRENT.json` plus the listed source documents.

Workflow: **{current['workflow_id']} {current['workflow_version']}**

Required Local Workspace profile: **{current['required_tool_profile']}**

## Fast-start contract

{fast_lines}

## Current user-evaluated productions

| Production | Status | Keep working | Baseline promoted |
| --- | --- | --- | --- |
{chr(10).join(rows)}

Machine-readable source: `productions/quality-status.json`.

## Canonical documents — consult as needed

""" + "\n".join(f"- `{p}`" for p in docs) + "\n"

def main() -> int:
    ap=argparse.ArgumentParser()
    ap.add_argument("--lane",choices=["cinematic","animation","business"],default="cinematic")
    ap.add_argument("--output")
    ap.add_argument("--check",action="store_true")
    args=ap.parse_args()
    text=render(args.lane)
    output=Path(args.output) if args.output else ROOT/"workflow"/f"{args.lane}-brief.md"
    if not output.is_absolute(): output=ROOT/output
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != text:
            print(f"FAIL generated lane brief is stale: {output.relative_to(ROOT)}")
            return 1
        print(f"PASS generated lane brief: {output.relative_to(ROOT)}")
        return 0
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(text,encoding="utf-8")
    print(output)
    return 0

if __name__=="__main__":
    raise SystemExit(main())