#!/usr/bin/env python3
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

def render(lane: str) -> str:
    current=json.loads((ROOT/"workflow/CURRENT.json").read_text(encoding="utf-8"))
    status=json.loads((ROOT/"productions/quality-status.json").read_text(encoding="utf-8"))
    docs=[]
    brief_path=str((current.get("lane_briefs") or {}).get(lane) or "")
    for p in list(current.get("core_docs") or [])+list((current.get("lane_docs") or {}).get(lane) or []):
        if p != brief_path and p not in docs: docs.append(p)
    rows=[]
    for item in status.get("productions",[]):
        if item.get("current"):
            rows.append(f"| {item['title']} | {item['user_quality_status']} | {'yes' if item['keep_working'] else 'no'} | {'yes' if item['baseline_promoted'] else 'no'} |")
    return f"""# {lane.title()} lane brief

> Generated by `scripts/generate-lane-brief.py`. Canonical policy remains `workflow/CURRENT.json` plus the listed source documents.

Workflow: **{current['workflow_id']} {current['workflow_version']}**

Required Local Workspace profile: **{current['required_tool_profile']}**

## Fast-start contract

1. Run Local Workspace `video_workflow_bootstrap` for the {lane} lane before serious production work.
2. Treat the returned receipt and live bridge compatibility as execution controls; final bind and render dispatch recheck the running bridge.
3. Technical validity, reproducibility, tests and hashes prove process control, not cinematic quality.
4. **Respectful means worth preserving/continuing, not finished, release-ready or baseline-promoted.**
5. For cinematic work, prove moving previs, representative look-dev, semantic motion, environment completeness, audio/visual synchronization and a freely seekable review player before claiming readiness.
6. User quality judgment controls promotion. Failed/weak candidates are learning evidence, not quality baselines.

## Current user-evaluated productions

| Production | Status | Keep working | Baseline promoted |
| --- | --- | --- | --- |
{chr(10).join(rows)}

Machine-readable source: `productions/quality-status.json`.

## Canonical documents

""" + "\n".join(f"- `{p}`" for p in docs) + "\n"

def main() -> int:
    ap=argparse.ArgumentParser()
    ap.add_argument("--lane",choices=["cinematic","animation","business"],default="cinematic")
    ap.add_argument("--output")
    ap.add_argument("--check",action="store_true")
    args=ap.parse_args()
    text=render(args.lane)
    output=Path(args.output) if args.output else ROOT/"workflow"/f"{args.lane}-brief.md"
    if not output.is_absolute(): output=ROOT/output
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != text:
            print(f"FAIL generated lane brief is stale: {output.relative_to(ROOT)}")
            return 1
        print(f"PASS generated lane brief: {output.relative_to(ROOT)}")
        return 0
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(text,encoding="utf-8")
    print(output)
    return 0

if __name__=="__main__":
    raise SystemExit(main())